name: Build and Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you use (e.g., main or master)
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'  # Specify the Ruby version you need for your Jekyll site

    - name: Build and test
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.event_name == 'push'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
